### ISSUE TITLE
Add trainId to Schedule object

### ISSUE THREAD

**Issue by vladvelici** [HackPartners/darwinpush#2]
The trainId attribute in the XML is missing from the objects, or at least is seems to be missing.

XML example:

```
<Journey rid="201509241060735" uid="Y57914" trainId="5S20" ssd="2015-09-24" toc="GR" trainCat="EE" isPassengerSvc="false">
  <OPOR tpl="ABRDEEN" act="TB" plat="5" wtd="21:25" />
  <OPIP tpl="ABRD27" act="OP" wta="21:30" wtd="21:40" />
  <OPDT tpl="ABRDCH" act="TF" wta="21:45" />
</Journey>
```

**Comment by axsaucedo** [comment]
Ah I did not know we were missing this attribute! Yes, I think we should definitely add it. It would be a good opportunity to use Arnold in the live code.

**Comment by axsaucedo** [comment]
Oh Vlad, we actually do store trainId, but we do so under the name 'heatcode'.

**Comment by axsaucedo** [comment]
Shall we close this issue, or do we want to rename the field to trainid?

**Comment by vladvelici** [comment]
Oh, didn't realise. Checked the code now. It's fine if it's headcode, it's also documented but didn't see that. My bad. Issue closed.
